# Generated by Django 3.1.2 on 2020-11-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_profileuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileuser',
            old_name='lastname',
            new_name='surnames',
        ),
    ]
